import type { SpikeScenarioDefinition } from '../types'

export const spikeScenarioDefinitions: ReadonlyArray<SpikeScenarioDefinition> = [
  {
    id: 'arbitrary-dom',
    title: 'Arbitrary live DOM backdrop',
    blocking: ['B-1'],
    visual: true,
    variants: ['native-svg', 'backdrop-blur', 'css-approximation', 'solid'],
    description: 'Real page content behind the lens; no readable texture exists.',
  },
  {
    id: 'controlled-image',
    title: 'Controlled image source',
    blocking: ['B-2'],
    visual: true,
    variants: ['sdf', 'transmission', 'css-approximation', 'solid'],
    description: 'A source the application owns and can hand to WebGL as a texture.',
  },
  {
    id: 'fallback-edges',
    title: 'Fallback edges',
    blocking: ['B-3'],
    visual: true,
    variants: [
      'webgl-creation-failure',
      'image-load-failure',
      'source-readability-failure',
      'reduced-transparency',
      'advanced-effects-disabled',
      'native-displacement-unavailable',
    ],
    description: 'Which downgrade edges can be forced without a production seam.',
  },
  {
    id: 'transformed-target',
    title: 'Transformed target geometry',
    blocking: ['B-4'],
    visual: true,
    variants: ['coupled', 'stationary', 'coupled-sdf'],
    description: 'Measured target rect versus observable lens geometry, per frame.',
  },
  {
    id: 'teardown',
    title: 'Teardown and retained resources',
    blocking: ['B-5'],
    visual: false,
    variants: ['sdf', 'css'],
    amounts: [1, 10, 50],
    description: 'Repeated mount/unmount; DOM- and JS-side retention only.',
  },
  {
    id: 'context-loss',
    title: 'Context loss and recovery',
    blocking: ['B-6'],
    visual: false,
    variants: ['default'],
    description: 'Current recovery behaviour after WEBGL_lose_context.',
  },
  {
    id: 'scope-sweep',
    title: 'Simultaneous scopes',
    blocking: ['B-7', 'B-8'],
    visual: true,
    variants: ['sdf', 'css'],
    amounts: [1, 2, 4, 8],
    description: 'Cold creation, steady frame cost and memory at 1/2/4/8 groups.',
  },
  {
    id: 'scroll-and-portal',
    title: 'Scroll containers and portals',
    blocking: ['B-4'],
    visual: true,
    variants: ['vertical-scroll', 'horizontal-scroll', 'portal'],
    description: 'Geometry drift across scroll and portal boundaries.',
  },
]
