import { type HeaderPlaygroundState } from '../types'

export const HEADER_DEFAULT_STATE: HeaderPlaygroundState = {
  variant: 'glassDark',
  size: 'lg',
  blurIntensity: 'xl',
  showGlow: true,
  glowColor: '#2dd4bf',
  initialWidth: 92,
  collapsedWidth: 58,
  topOffset: 16,
  borderRadiusExpanded: 22,
  borderRadiusCollapsed: 999,
  collapseBehavior: 'scroll',
  collapsed: false,
  hideNavOnCollapse: true,
  hideOnScrollDown: true,
  scrollDistance: 220,
  collapseThreshold: 0.58,
  motionPreset: 'spring',
  smoothScrollMotion: true,
  showLogo: true,
  showNavigation: true,
  showActions: true,
  activeNavItem: 'overview',
  showDisabledNavItem: true,
  loadingPrimaryAction: false,
  primaryActionVariant: 'default',
}
